services:
  bstheme.listener.install_command:
    class: Fipps\BootstrapCustomizerBundle\Listener\InstallCommandListener
    arguments:
      - "%kernel.kernel.project_dir%"
    tags:
      - { name: kernel.event_listener, event: console.terminate }
