services:
  bstheme.listener.install_command:
    class: Fipps\BootstrapCustomizerBundle\Listener\InstallCommandListener
    arguments:
      - "%kernel.root_dir%"
    tags:
      - { name: kernel.event_listener, event: console.terminate }

  craft.colormixertwigextension:
    class: Craft\ColorMixerTwigExtension
    tags:
      - { name: twig.extension }
